version: "3"
services:
  monitoring_ebt:
    build: ./monitoring_ebt
    ports:
      - "5005:5005"
    stdin_open: true
    tty: true
    # volumes:
    #   - /app/node_modules
    #   - ./monitoring_ebt:/app